version: '3.9'
services:
  api:
    build: ../../backend
    ports:
      - "8080:8080"
  worker:
    build: ../../worker
    depends_on:
      - api
  frontend:
    build: ../../frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
